crud/accounts/urls.py
#urls for accounts app
from django.urls import path
# urls for auth views
from django.contrib.auth import views as auth_views
#viwews for accounts app
from . import views

app_name = 'accounts'
# URL patterns for the accounts app
urlpatterns = [
    path(
        'login/', 
        auth_views.LoginView.as_view(template_name='accounts/login.html'), 
        name='login'
    ),
    path(
        'logout/', 
        auth_views.LogoutView.as_view(), 
         name='logout'
         ),
    path(
        'logout_message/',
        views.LogoutMessageView.as_view(),
        name='logout_message'
    ),
    path(
        'signup/', 
         views.SignUpView.as_view(), 
         name='signup'
         ),
]

crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('persona/', include('persona.urls')),
    path('accounts/', include('accounts.urls')),
]

crud/persona/urls.py
from django.urls import path
from .views import *

app_name = 'persona'

urlpatterns = [
    path(
        'lista/',
        PersonaListView.as_view(),
        name='lista'
    ),
    path(
        'buscar/',
        PersonaSearchView.as_view(),
        name='buscar'
    ),
    path(
        'detalle/<int:pk>/',
        PersonaDetailView.as_view(),
        name='detalle'
    ),
    path(
        'crear/',
        PersonaCreateView.as_view(),
        name='crear'
    ),
    path(
        'editar/<int:pk>/',
        PersonaUpdateView.as_view(),
        name='editar'
    ),
    path(
        'eliminar/<int:pk>/',
        PersonaDeleteView.as_view(),
        name='eliminar'
    ),
]

crud/accounts/models.py
from django.db import models

# Create your models here.

crud/persona/models.py
from django.db import models

class Persona(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=50)
    edad = models.IntegerField(verbose_name="Edad")
    email = models.EmailField(verbose_name="Correo Electrónico", max_length=254)

    class Meta:
        verbose_name = "Persona"
        verbose_name_plural = "Personas"

    def __str__(self):
        return f"{self.nombre} - {self.email}"

crud/accounts/views.py
from django.shortcuts import render

# Create your views here.
#CBV for signup view
from django.views.generic import CreateView, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm

class SignUpView(CreateView):
    template_name = 'accounts/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Sign Up'
        return context

class LogoutMessageView(TemplateView):
    template_name = 'accounts/logout_message.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Desloguearse'
        return context

crud/persona/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Persona
from django.db.models import Q  
# Import login mixin if needed
from django.contrib.auth.mixins import LoginRequiredMixin


class PersonaListView(ListView):
    model = Persona
    template_name = 'persona/lista.html'
    context_object_name = 'personas'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "Lista de Personas"
        return context

class PersonaSearchView(ListView):
    model = Persona
    template_name = 'persona/buscar.html'
    context_object_name = 'personas'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Persona.objects.filter(
                Q(nombre__icontains=query)     
            )
        return Persona.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "Buscar Personas"
        context['search_query'] = self.request.GET.get('q', '')
        return context

class PersonaDetailView(DetailView):
    model = Persona
    template_name = 'persona/detalle.html'
    context_object_name = 'persona'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "Detalle de Personas"
        return context
class PersonaCreateView(LoginRequiredMixin, CreateView):
    model = Persona
    template_name = 'persona/crear.html'
    fields = ['nombre', 'edad', 'email']
    success_url = reverse_lazy('persona:lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "Nueva Persona"
        return context
    
class PersonaUpdateView(LoginRequiredMixin, UpdateView):
    model = Persona
    template_name = 'persona/crear.html'
    fields = ['nombre', 'edad', 'email']
    success_url = reverse_lazy('persona:lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "Editar Persona"
        return context
    
class PersonaDeleteView(LoginRequiredMixin, DeleteView):
    model = Persona
    template_name = 'persona/eliminar.html'
    context_object_name = 'persona'
    success_url = reverse_lazy('persona:lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "Borrar Persona"
        context['confirm_message'] = "¿Estás seguro de que quieres eliminar esta persona?"  
        context['cancel_url'] = reverse_lazy('persona:lista')
        return context

crud/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Iniciar Sesión</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Iniciar Sesión</button>
    <p>No tienes una cuenta? <a href="{% url 'accounts:signup' %}">Registrate</a></p>
  </form>
{% endblock %}

crud/templates/accounts/logout_message.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" action="{% url 'accounts:logout' %}">
        {% csrf_token %}
        <h1>{{ title }}</h1>
        {{ form.as_p }}
        <h2>¿Seguro que quieres cerrar sesión?</h2>
        <button type="submit">Cerrar Sesión</button>
        <p>¿No quieres cerrar sesión? <a href="{% url 'persona:lista' %}">Volver</a></p>
    </form>
{% endblock %}

crud/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>{{ title }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
    <p>Ya tienes una cuenta? <a href="{% url 'accounts:login' %}">Log in</a></p>
  </form>
{% endblock %}

crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>
    <title>CRUD</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
       
    {% endblock content %}

</body>
</html>

crud/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="{% url 'persona:buscar' %}">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"name="q">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

crud/templates/persona/buscar.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ titulo }}</h1>
    <form method="get">
        <input type="text" name="q" placeholder="Buscar persona..." value="{{ query }}">
        <button type="submit">Buscar</button>
    </form>
    {% if personas %}
        <h1>Resultados</h1>
        <ul>
            {% for persona in personas %}
                <li>{{ persona }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Resultados:</p>
    {% endif %}
{% endblock content %}

crud/templates/persona/crear.html
{% extends 'base.html' %}

{% block content %}
<h1>Crear / Editar Persona</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
    <a href="{% url 'persona:lista' %}">Volver a la lista</a>
</form>
{% endblock %}

crud/templates/persona/detalle.html
{% extends 'base.html' %}

{% block content %}
  <h1>Detalle de Persona</h1>
  <p><strong>Nombre:</strong> {{ persona.nombre }}</p>
  <p><strong>Edad:</strong> {{ persona.edad }}</p>
  <p><strong>Email:</strong> {{ persona.email }}</p>

  <a href="{% url 'persona:lista' %}">Volver a la lista</a>

{% endblock %}

crud/templates/persona/eliminar.html
{% extends 'base.html' %}

{% block content %}
  <h1>Eliminar Persona</h1>
  <p>¿Estás seguro de que deseas eliminar a {{ persona.nombre }}?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirmar Eliminación</button>
  </form>
  <a href="{% url 'persona:lista' %}">Volver a la lista</a>
{% endblock %}

crud/templates/persona/lista.html
{% extends 'base.html' %}


{% block content %}
    <h1>{{ titulo }}</h1>
    {% if personas %}
        <ul>
            {% for persona in personas %}
                <li>{{ persona }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock content %}
    